
server:
  port: 80
  servlet:
    context-path: /shiro

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    hikari:
      auto-commit: true
      maximum-pool-size: 10

  profiles:
    include:
      - menu
      - mybatis
      - custom
  thymeleaf:
    cache: false #\u7F13\u5B58
    enabled: true   #\u542F\u7528
    encoding: UTF-8 #\u7F16\u7801
    prefix: classpath:/template/  #\u524D\u7F00
    suffix: .html
    mode: HTML #\u9875\u9762
  http:
    encoding:
      charset: UTF-8


