custom:
  permission:
    menu[0]:
      id: 1
      parentId: 0
      name: 用户管理
      permission: userPage
      type: 0
      author: lrfc
    menu[1]:
      id: 2
      parentId: 0
      name: 角色管理
      permission: rolePage
      type: 0
      author: lrfc
    menu[2]:
      id: 3
      parentId: 0
      name: 资源管理
      permission: resourcePage
      type: 0
      author: lrfc

